update_fastlane
default_platform(:ios)

platform :ios do
  ltbn = latest_testflight_build_number(api_key_path: "fastlane/api_key.json")

  lane :beta do
    increment_build_number(
      build_number: ltbn + 1,
      xcodeproj: "BetterTG.xcodeproj",
    )
    get_certificates
    get_provisioning_profile
    build_app(
      scheme: "BetterTG",
      configuration: "Debug",
    )
    upload_to_testflight(
      ipa: "BetterTG.ipa",
      api_key_path: "fastlane/api_key.json",
      changelog: "First build",
    )
  end

  lane :release do
    increment_build_number(
      build_number: ltbn + 1,
      xcodeproj: "BetterTG.xcodeproj",
    )
    get_certificates
    get_provisioning_profile
    build_app(
      scheme: "BetterTG",
      configuration: "Release",
    )
    upload_to_app_store(
      api_key_path: "fastlane/api_key.json",
      skip_metadata: true,
      skip_screenshots: true,
    )
  end
end
